# Generated by Django 6.0.8 on 2026-10-08 02:33
#
# host, os_user and os_group (computing-core#8, #27). The retired `user` model is dropped by
# 0008 after 0007 removes its rows; this file only creates.

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computing_core", "0005_retire_document_edge_types"),
        ("tap_grid", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalHost",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The authority that issued stable_id (aws-ec2, github-runner, machine-id, assert, ...).",
                        max_length=64,
                    ),
                ),
                (
                    "stable_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The host's identifier within realm. Never the hostname.",
                        max_length=255,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Display name; usually the hostname.",
                        max_length=255,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="One of HOST_KINDS. Null = not observed; 'unknown' = looked and could not tell.",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The operating system as reported (linux, macOS 15.6, Windows Server 2022).",
                        max_length=255,
                    ),
                ),
                (
                    "ephemeral",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        help_text="True when nothing survives between uses (a hosted CI runner). Null = not observed.",
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical host",
                "verbose_name_plural": "historical hosts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOsGroup",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "host_realm",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The defining host's realm.",
                        max_length=64,
                    ),
                ),
                (
                    "host_stable_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The defining host's stable_id.",
                        max_length=255,
                    ),
                ),
                (
                    "local_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The SID on Windows; the group name on POSIX. Identity within the host.",
                        max_length=255,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The group name as reported.",
                        max_length=255,
                    ),
                ),
                (
                    "gid",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="POSIX numeric group id. Null on Windows or when not observed.",
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical os group",
                "verbose_name_plural": "historical os groups",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOsUser",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "host_realm",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The defining host's realm.",
                        max_length=64,
                    ),
                ),
                (
                    "host_stable_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The defining host's stable_id.",
                        max_length=255,
                    ),
                ),
                (
                    "local_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The SID on Windows; the login name on POSIX. Identity within the host.",
                        max_length=255,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The account name as reported.",
                        max_length=255,
                    ),
                ),
                (
                    "uid",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="POSIX numeric user id. Null on Windows or when not observed.",
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical os user",
                "verbose_name_plural": "historical os users",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The authority that issued stable_id (aws-ec2, github-runner, machine-id, assert, ...).",
                        max_length=64,
                    ),
                ),
                (
                    "stable_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The host's identifier within realm. Never the hostname.",
                        max_length=255,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Display name; usually the hostname.",
                        max_length=255,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="One of HOST_KINDS. Null = not observed; 'unknown' = looked and could not tell.",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The operating system as reported (linux, macOS 15.6, Windows Server 2022).",
                        max_length=255,
                    ),
                ),
                (
                    "ephemeral",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        help_text="True when nothing survives between uses (a hosted CI runner). Null = not observed.",
                        null=True,
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "computing_core__host",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OsGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "host_realm",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The defining host's realm.",
                        max_length=64,
                    ),
                ),
                (
                    "host_stable_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The defining host's stable_id.",
                        max_length=255,
                    ),
                ),
                (
                    "local_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The SID on Windows; the group name on POSIX. Identity within the host.",
                        max_length=255,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The group name as reported.",
                        max_length=255,
                    ),
                ),
                (
                    "gid",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="POSIX numeric group id. Null on Windows or when not observed.",
                        null=True,
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "computing_core__os_group",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OsUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "host_realm",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The defining host's realm.",
                        max_length=64,
                    ),
                ),
                (
                    "host_stable_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The defining host's stable_id.",
                        max_length=255,
                    ),
                ),
                (
                    "local_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The SID on Windows; the login name on POSIX. Identity within the host.",
                        max_length=255,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The account name as reported.",
                        max_length=255,
                    ),
                ),
                (
                    "uid",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="POSIX numeric user id. Null on Windows or when not observed.",
                        null=True,
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "computing_core__os_user",
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="host",
            index=models.Index(
                fields=["realm", "stable_id"], name="nk_computing_core__host"
            ),
        ),
        migrations.AddIndex(
            model_name="osgroup",
            index=models.Index(
                fields=["host_realm", "host_stable_id", "local_id"],
                name="nk_computing_core__os_group",
            ),
        ),
        migrations.AddIndex(
            model_name="osuser",
            index=models.Index(
                fields=["host_realm", "host_stable_id", "local_id"],
                name="nk_computing_core__os_user",
            ),
        ),
    ]
